'use client';
// export * as client from './Clients';
export { Navbar } from './Navbar';
export { Scrollbar } from './HorizontalScrollbar';
// export { Hero } from '../Hero';
export { BackToTop } from './BackToTop';
export { About } from './About';
export { Skills } from './Skills';
export { Projects } from './Projects';
export { Contact } from './Contact';
// export default BallCanvas from './Ball';